### ISSUE TITLE
enhance PL translations

### ISSUE THREAD

**Issue by az** [eventjuicer/aor-translations#1]
i think it should be more imperative/action like

ZAPROŚ

![expojuicer com 2018-03-21 01-09-15](https://user-images.githubusercontent.com/2198/37689307-90361d3e-2ca4-11e8-90c8-d2493ae0dd79.png)

**Comment by bartek19** [comment]
I agree, changed! I removed also Domain field because nobody adds it and it causes that if Position field is too long, "Zaproś" is not visible.
![expojuicer com 4](https://user-images.githubusercontent.com/36699450/37711605-879fa416-2d11-11e8-83bc-678b7567ad31.png)
