### ISSUE TITLE
when defining components, functions, props,  please follow conventions OR best practices

### ISSUE THREAD

**Issue by az** [eventjuicer/aor-translations#13]
![zrzut ekranu 2018-03-29 o 22 24 04](https://user-images.githubusercontent.com/2198/38132375-1ee5c1f2-340b-11e8-8c97-80ee48b8740e.png)

- ComponentName
- function_name or functionName (should be consisted within a project)
- propsName
- JS object/JSON key_name

**Comment by bartek19** [comment]
corrected, but I will use props in component when defining just one custom element 

![zrzut ekranu 2018-03-30 o 13 36 49](https://user-images.githubusercontent.com/36699450/38136558-784ea8b2-341f-11e8-90a4-463599435d60.png)
