### ISSUE TITLE
no access/login screen should be translated

### ISSUE THREAD

**Issue by az** [eventjuicer/aor-translations#3]
![expojuicer com 2018-03-21 01-14-35](https://user-images.githubusercontent.com/2198/37689465-546ccaf4-2ca5-11e8-905c-9f3428198a31.png)

**Comment by az** [comment]
also WTF is Niezautorywany @bartek19  ? :) ... Brak dostępu.

**Comment by bartek19** [comment]
translated, 'brak dostępu' sounds a little bit better :)
